# Generated by Django 5.1.1 on 2024-10-13 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_cc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clube',
            name='favoritado',
        ),
        migrations.AddField(
            model_name='clube',
            name='favoritos',
            field=models.ManyToManyField(blank=True, related_name='clubes_favoritos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('icone', models.CharField(blank=True, max_length=255, null=True)),
                ('seguindo', models.ManyToManyField(blank=True, related_name='seguidores', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
