# Generated by Django 5.1 on 2024-09-20 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_cc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3, unique=True)),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='clube',
            name='categoria',
            field=models.ForeignKey(blank=True, default='Sem categoria', null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_cc.categoria'),
        ),
        migrations.AlterField(
            model_name='clube',
            name='modalidade',
            field=models.ForeignKey(blank=True, default='Sem modalidade', null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_cc.modalidade'),
        ),
    ]
