# Generated by Django 5.1 on 2024-10-12 14:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_cc', '0002_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='seguindo',
            field=models.ManyToManyField(blank=True, related_name='seguidores', to=settings.AUTH_USER_MODEL),
        ),
    ]
