# Generated by Django 5.1.1 on 2024-10-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_cc', '0002_remove_clube_favoritado_clube_favoritos_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='clube',
            name='top_livros',
            field=models.TextField(blank=True, null=True),
        ),
    ]
