# Generated by Django 5.1 on 2024-09-20 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_cc', '0002_modalidade_alter_clube_categoria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='descricao',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='modalidade',
            old_name='descricao',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='modalidade',
            name='codigo',
        ),
    ]
