# Generated by Django 5.1 on 2024-09-21 11:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_cc', '0003_rename_descricao_categoria_nome_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='clube',
            old_name='avaliacoes',
            new_name='mediaAvaliacoes',
        ),
        migrations.AddField(
            model_name='clube',
            name='numAvaliacoes',
            field=models.ManyToManyField(related_name='avaliacoes', to=settings.AUTH_USER_MODEL),
        ),
    ]
