# Generated by Django 5.1 on 2024-09-21 13:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_cc', '0004_rename_avaliacoes_clube_mediaavaliacoes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clube',
            name='numAvaliacoes',
        ),
        migrations.AddField(
            model_name='clube',
            name='avaliacoes',
            field=models.ManyToManyField(blank=True, related_name='avaliacoes', to=settings.AUTH_USER_MODEL),
        ),
    ]
