# Generated by Django 5.1.1 on 2024-10-13 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_cc', '0004_remove_comentario_nome_comentario_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='clube',
            name='capitulo_final_maratona',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clube',
            name='data_fim_maratona',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clube',
            name='maratona_ativa',
            field=models.BooleanField(default=False),
        ),
    ]
