# Generated by Django 5.1 on 2024-10-13 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_cc', '0004_profile_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='icon',
            new_name='icone',
        ),
    ]
