# Generated by Django 5.1 on 2024-09-21 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_cc', '0004_membro'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='motivo_recusa',
            field=models.TextField(blank=True, null=True),
        ),
    ]
