# Generated by Django 5.1.1 on 2024-10-13 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_cc', '0005_clube_capitulo_final_maratona_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clube',
            name='nome_maratona',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
