# Generated by Django 5.1.1 on 2024-10-14 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_cc', '0006_clube_nome_maratona'),
    ]

    operations = [
        migrations.AddField(
            model_name='clube',
            name='data_inicio_maratona',
            field=models.DateField(blank=True, null=True),
        ),
    ]
