# Generated by Django 5.1 on 2024-09-21 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_cc', '0006_avaliacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clube',
            name='avaliacoes',
        ),
        migrations.RemoveField(
            model_name='clube',
            name='livroAtual',
        ),
        migrations.RemoveField(
            model_name='clube',
            name='mediaAvaliacoes',
        ),
    ]
