# Generated by Django 5.1.1 on 2024-10-14 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_cc', '0007_clube_data_inicio_maratona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clube',
            name='data_inicio_maratona',
        ),
    ]
