# Generated by Django 5.1 on 2024-09-21 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_cc', '0005_membro_motivo_recusa'),
        ('site_cc', '0007_remove_clube_avaliacoes_remove_clube_livroatual_and_more'),
    ]

    operations = [
    ]
