# Generated by Django 5.1 on 2024-09-21 19:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_cc', '0008_merge_20240921_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clube',
            name='descricao',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
