# Generated by Django 5.1.1 on 2024-10-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_cc', '0008_remove_clube_data_inicio_maratona'),
    ]

    operations = [
        migrations.AddField(
            model_name='clube',
            name='total_maratona_finalizadas',
            field=models.IntegerField(default=0),
        ),
    ]
