# Generated by Django 5.1 on 2024-09-21 20:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_cc', '0009_alter_clube_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='clube',
            name='sobre',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clube',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
