# Generated by Django 5.1.1 on 2024-10-14 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_cc', '0009_clube_total_maratona_finalizadas'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoMaratona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_maratona', models.CharField(max_length=255)),
                ('data_fim', models.DateField()),
                ('capitulo_final', models.CharField(max_length=255)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('clube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_cc.clube')),
            ],
        ),
    ]
