# Generated by Django 5.1.1 on 2024-10-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_cc', '0010_historicomaratona'),
    ]

    operations = [
        migrations.AddField(
            model_name='clube',
            name='data_inicio_maratona',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicomaratona',
            name='data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
