# Generated by Django 5.1 on 2024-09-21 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_cc', '0011_comentario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='comment',
            new_name='comentario',
        ),
    ]
