# Generated by Django 5.1.1 on 2024-10-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_cc', '0011_clube_data_inicio_maratona_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clube',
            name='capitulo_inicial_maratona',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicomaratona',
            name='capitulo_inicial',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
