# Generated by Django 5.1.1 on 2024-10-14 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_cc', '0012_clube_capitulo_inicial_maratona_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clube',
            old_name='capitulo_inicial_maratona',
            new_name='capitulo_atual_maratona',
        ),
        migrations.RenameField(
            model_name='historicomaratona',
            old_name='capitulo_inicial',
            new_name='capitulo_atual',
        ),
    ]
