# Generated by Django 5.1 on 2024-09-26 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_cc', '0012_rename_comment_comentario_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clube',
            name='sobre',
            field=models.TextField(blank=True, null=True),
        ),
    ]
