# Generated by Django 5.1.1 on 2024-10-15 17:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_cc', '0013_rename_capitulo_inicial_maratona_clube_capitulo_atual_maratona_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='seguindo',
        ),
        migrations.AddField(
            model_name='profile',
            name='seguidores',
            field=models.ManyToManyField(blank=True, related_name='seguindo', to=settings.AUTH_USER_MODEL),
        ),
    ]
