# Generated by Django 5.1.1 on 2024-09-27 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_cc', '0013_alter_clube_sobre'),
    ]

    operations = [
        migrations.AddField(
            model_name='clube',
            name='progresso_atual',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clube',
            name='total_capitulos',
            field=models.IntegerField(default=50),
        ),
    ]
