# Generated by Django 5.1.1 on 2024-10-31 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_cc', '0015_enquete_opcao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_voto', models.DateTimeField(auto_now=True)),
                ('enquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_cc.enquete')),
                ('opcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_cc.opcao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'enquete')},
            },
        ),
    ]
